config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins
  get 'welcome/index'
  root 'welcome#index'
  get 'mypins' => 'pins#mypins'
  get 'pinsof/:user_id' => 'pins#pinsof', :as => 'pinsof'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
    validates :photo, presence:true
    validates :description, presence:true

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :phone) }
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  def mypins
    @pins = current_user.pins
  end

  def pinsof
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    @pins = @user.pins
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ"
          crossorigin="anonymous">

  </head>

  <body>
    <%= render 'shared/navbar' %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.label :Name, "Nombre" %>
      <%= form.text_field :name, :class=>'form-control', :placeholder=>'Nombre del Pins' %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
        <%= form.label :photo, "Foto" %>
        <%= form.text_field :photo , :class=>'form-control', :placeholder=>'Url de la foto' %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= form.label :description, "Descripcion" %>
      <%= form.text_area :description, :class=>'form-control', :rows=>'10' %>
    </div>
  </div>




  <div class="actions">
    <%= form.submit 'Crear', :class=>'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>Editing Pin</h1>

            <%= render 'form', pin: @pin %>
        </div>
    </div>
    <%= link_to 'Show', @pin %>
    <%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>
<div class='container'>
    <h1>Pins</h1>
    <% @pins.each do |pin| %>
        <div class="col-md-3">
            <div class="thumbnail">
                <%= pin.description %>
                <%= image_tag(pin.photo, :class => 'img-responsive') %>
                <div class="buttons" style="margin-top: 10px; margin-bottom: 10px">
                    <%= link_to 'Show', pin, :class => 'btn btn-primary' %>
                    <% if user_signed_in? %>
                        <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn btn-primary' %>
                        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-primary'%>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
    <br>

    <% if user_signed_in? %>
        <%= link_to 'New Pin', new_pin_path %>
    <% end %>
</div>

app/views/pins/mypins.html.erb
<p id="notice"><%= notice %></p>
<div class='container'>
    <h1>Mis Pins</h1>
    <% @pins.each do |pin| %>
        <div class="col-md-3">
            <div class="thumbnail">
                <%= pin.description %>
                <%= image_tag(pin.photo, :class => 'img-responsive') %>
                <div class="buttons" style="margin-top: 10px; margin-bottom: 10px">
                    <%= link_to 'Show', pin, :class => 'btn btn-primary' %>
                    <% if user_signed_in? %>
                        <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn btn-primary' %>
                        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-primary'%>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
    <br>

    <% if user_signed_in? %>
        <%= link_to 'New Pin', new_pin_path %>
    <% end %>
</div>

app/views/pins/new.html.erb
<div class="container">
    <h1>Crea nuevo Pin</h1>
    <div class="row">
        <div class="col-md-6">
            <%= render 'form', pin: @pin %>
        </div>
    </div>
    <p><%= link_to 'Back', pins_path %></p>

</div>

app/views/pins/pinsof.html.erb
<%= @user_id %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Name:</strong>
    <%= @pin.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style => 'width: 300px') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %>
<%= link_to 'Back', pins_path %>

<%= link_to "Mas pins del mismo usuario" , pinsof_path(@pin.user.id) %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:0px">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Mi Pinterest</a>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
            <a class="nav-link" href="<%= root_path %>">Nosotros <span class="sr-only">(current)</span></a>
            </li>
            <li><a class="nav-link" href="<%= mypins_path %>">Mis Pins</a></li>
            <li class="nav-item">
            <a class="nav-link" href="<%= pins_path %>">Pins</a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <% if current_user.nil? %>
                <li><a href="<%= new_user_session_path %>">Ingreso</a></li>
                <li><a href="<%= new_user_registration_path %>">Registro</a></li>
            <% else %>
                <li><a href="<%= destroy_user_session_path %>" data-method="delete">Salir</a></li>
            <% end %>
        </ul>

    </div>
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
    <h1 style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">Titulo</h1>
    <h2>SubTitulo</h2>
    <h3>SubSubTitulo</h3>
    <a href="http://en1mes.com" class="btn btn-primary">
        En1Mes
        <span class="fab fa-android" style="color:red"></span>
    </a>
</div>
<div class="container">
    <div class="row">
    <div class="col-md-4">
        <div class="page-header">
            <h3 style="display: inline;">Ejemplo de page header</h3>
            <span class="badge">New</span>
        </div>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis, aut harum officia, corporis quis est distinctio vitae molestias aliquam nostrum cum error magnam pariatur? Doloremque accusamus cum odio dolores tempora?</p>
    </div>

    <div class="col-md-4">
        <div class="page-header">
            <h2>Ejemplo de page header</h2>
        </div>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis, aut harum officia, corporis quis est distinctio vitae molestias aliquam nostrum cum error magnam pariatur? Doloremque accusamus cum odio dolores tempora?</p>
    </div>

    <div class="col-md-4">
        <div class="page-header">
            <h2>Ejemplo de page header</h2>
        </div>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis, aut harum officia, corporis quis est distinctio vitae molestias aliquam nostrum cum error magnam pariatur? Doloremque accusamus cum odio dolores tempora?</p>
    </div>
    </div>
</div>
<img src="https://en1mes.com/assets/logo-5d8021b65a5944316da34b544b012157.png" alt="">
<hr>
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>